name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    env:
      TEST_ID_TESTNET: ${{ secrets.PROJECT_ID_MAINNET }}
      TEST_ID_IPFS: ${{ secrets.PROJECT_ID_IPFS }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate
      working-directory: examples

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Delete vendor obliterating permissions
      run: rm -Rf vendor
      working-directory: examples
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      working-directory: examples

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer run-script test
      working-directory: examples
      
